
services:
  phpi:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: phpi
    working_dir: /var/www
    environment:
      PHP_IDE_CONFIG: serverName=localhost
      SMTP_LOGIN: ${SMTP_LOGIN:-}
      SMTP_PASS: ${SMTP_PASS:-}
      BREVO_KEY: ${BREVO_KEY:-}
    volumes:
      - "./:/var/www:rw"

  nginxi:
    image: nginx:alpine
    container_name: nginxi
    ports:
      - "8282:80"
    volumes:
      - "./:/var/www:ro"
      - "./infra/local/nginx:/etc/nginx/conf.d/:ro"

  maileri:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  ###> doctrine/doctrine-bundle ###
  databasei:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "35432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

#  valkey:
#    image: valkey/valkey:8.1-alpine
#    container_name: valkey
#    ports:
#      - "6379:6379"
#    command: ["valkey-server", "--save", "", "--appendonly", "no"]

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
