<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260401162000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Align schema with Doctrine metadata and messenger transport table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');

        $this->addSql("COMMENT ON COLUMN invoice_item.quantity IS ''");
        $this->addSql("COMMENT ON COLUMN invoice_item.unit_price IS ''");
        $this->addSql('ALTER INDEX idx_5e3a44ab2989f1fd RENAME TO IDX_1DDE477B2989F1FD');

        $this->addSql("COMMENT ON COLUMN company.address IS ''");
        $this->addSql("COMMENT ON COLUMN invoice.issue_date IS ''");
        $this->addSql("COMMENT ON COLUMN invoice.due_date IS ''");
        $this->addSql("COMMENT ON COLUMN invoice.notes IS ''");
        $this->addSql("COMMENT ON COLUMN invoice.created_at IS ''");
        $this->addSql('ALTER INDEX idx_906517449e6f2849 RENAME TO IDX_906517441005651C');
        $this->addSql('ALTER INDEX idx_9065174452e5d129 RENAME TO IDX_90651744EF9B50A8');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');

        $this->addSql("COMMENT ON COLUMN invoice_item.quantity IS '(DC2Type:decimal)'");
        $this->addSql("COMMENT ON COLUMN invoice_item.unit_price IS '(DC2Type:decimal)'");
        $this->addSql('ALTER INDEX idx_1dde477b2989f1fd RENAME TO IDX_5E3A44AB2989F1FD');

        $this->addSql("COMMENT ON COLUMN company.address IS '(DC2Type:text)'");
        $this->addSql("COMMENT ON COLUMN invoice.issue_date IS '(DC2Type:date_immutable)'");
        $this->addSql("COMMENT ON COLUMN invoice.due_date IS '(DC2Type:date_immutable)'");
        $this->addSql("COMMENT ON COLUMN invoice.notes IS '(DC2Type:text)'");
        $this->addSql("COMMENT ON COLUMN invoice.created_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql('ALTER INDEX idx_906517441005651c RENAME TO IDX_906517449E6F2849');
        $this->addSql('ALTER INDEX idx_90651744ef9b50a8 RENAME TO IDX_9065174452E5D129');
    }
}
