<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260402114500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create invoice email delivery history table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE invoice_email_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, invoice_id INT NOT NULL, status VARCHAR(20) NOT NULL, recipient_email VARCHAR(180) NOT NULL, subject VARCHAR(255) NOT NULL, error_message TEXT DEFAULT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1A6A59882989F1FD ON invoice_email_log (invoice_id)');
        $this->addSql("COMMENT ON COLUMN invoice_email_log.error_message IS '(DC2Type:text)'");
        $this->addSql("COMMENT ON COLUMN invoice_email_log.sent_at IS '(DC2Type:datetime_immutable)'");
        $this->addSql('ALTER TABLE invoice_email_log ADD CONSTRAINT FK_1A6A59882989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE invoice_email_log DROP CONSTRAINT FK_1A6A59882989F1FD');
        $this->addSql('DROP TABLE invoice_email_log');
    }
}
