<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260401160000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create user, company, invoice and invoice item tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9E7927C74 ON app_user (email)');

        $this->addSql('CREATE TABLE company (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT NOT NULL, name VARCHAR(150) NOT NULL, type VARCHAR(30) NOT NULL, tax_id VARCHAR(120) DEFAULT NULL, country_code VARCHAR(2) NOT NULL, address TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4FBF094F7E3C61F9 ON company (owner_id)');
        $this->addSql('COMMENT ON COLUMN company.address IS \'(DC2Type:text)\'');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE invoice (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, owner_id INT NOT NULL, issuer_company_id INT NOT NULL, recipient_company_id INT NOT NULL, number VARCHAR(60) NOT NULL, issue_date DATE NOT NULL, due_date DATE DEFAULT NULL, currency VARCHAR(3) NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_906517449E6F2849 ON invoice (issuer_company_id)');
        $this->addSql('CREATE INDEX IDX_9065174452E5D129 ON invoice (recipient_company_id)');
        $this->addSql('CREATE INDEX IDX_906517447E3C61F9 ON invoice (owner_id)');
        $this->addSql('COMMENT ON COLUMN invoice.issue_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN invoice.due_date IS \'(DC2Type:date_immutable)\'');
        $this->addSql('COMMENT ON COLUMN invoice.notes IS \'(DC2Type:text)\'');
        $this->addSql('COMMENT ON COLUMN invoice.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_906517447E3C61F9 FOREIGN KEY (owner_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_906517449E6F2849 FOREIGN KEY (issuer_company_id) REFERENCES company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE invoice ADD CONSTRAINT FK_9065174452E5D129 FOREIGN KEY (recipient_company_id) REFERENCES company (id) NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE invoice_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, invoice_id INT NOT NULL, billing_type VARCHAR(30) NOT NULL, description VARCHAR(180) NOT NULL, quantity NUMERIC(10, 2) NOT NULL, unit_price NUMERIC(12, 2) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5E3A44AB2989F1FD ON invoice_item (invoice_id)');
        $this->addSql('COMMENT ON COLUMN invoice_item.quantity IS \'(DC2Type:decimal)\'');
        $this->addSql('COMMENT ON COLUMN invoice_item.unit_price IS \'(DC2Type:decimal)\'');
        $this->addSql('ALTER TABLE invoice_item ADD CONSTRAINT FK_5E3A44AB2989F1FD FOREIGN KEY (invoice_id) REFERENCES invoice (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE invoice DROP CONSTRAINT FK_906517449E6F2849');
        $this->addSql('ALTER TABLE invoice DROP CONSTRAINT FK_9065174452E5D129');
        $this->addSql('ALTER TABLE invoice_item DROP CONSTRAINT FK_5E3A44AB2989F1FD');
        $this->addSql('ALTER TABLE company DROP CONSTRAINT FK_4FBF094F7E3C61F9');
        $this->addSql('ALTER TABLE invoice DROP CONSTRAINT FK_906517447E3C61F9');
        $this->addSql('DROP TABLE invoice');
        $this->addSql('DROP TABLE invoice_item');
        $this->addSql('DROP TABLE company');
        $this->addSql('DROP TABLE app_user');
    }
}
